baseURL: "/"
title: Jonathan Roth
paginate: 5
theme: hugo-PaperMod
 
enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
# googleAnalytics: UA-123-45

minify:
    disableXML: true
    # minifyOutput: true

languages:
    en:
        languageName: "English"
        languageAltTitle: "English"
        weight: 2
        title: 
        profileMode:
            enabled: true
            title: "Jonathan Roth"
            imageUrl: "avatar.jpg"
            imageWidth: 256
            imageHeight: 256
            subtitle: "grateful for where my love of mathematics has taken me"
            buttons:

        menu:
            main:
                - name: Home
                  url: / 
                  weight: 10
                    #- name: About Me
                    #url: about_me/
                    #weight: 20
                - name: Projects
                  url: projects
                  weight: 30
                  #- name: Posts
                  #url: posts/
                  #weight: 40
                - name: Search
                  url: search/
                  weight: 50
                  #- name: Archive
                  #url: archive/
                  #weight: 60


outputs:
    home:
        - HTML
        - RSS
        - JSON

params:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    description: "Jonathan Roth Blog"
    author: Jonathan Roth

    defaultTheme: dark
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    displayFullLangName: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    ShowToc: true

    socialIcons:
        - name: github
          url: "https://github.com/JonathanRoth13"
        - name: linkedin
          url: "https://www.linkedin.com/in/jonathanroth13/"
        - name: email
          url: "mailto:jonathanroth@protonmail.com"

    editPost:
        URL: "https://github.com/JonathanRoth13/JonathanRoth13.github.io/tree/hugo/content"
        Text: "Suggest Changes" # edit text
        appendFilePath: true # to append file path to Edit link





    # analytics:
    #     google:
    #         SiteVerificationTag: "XYZabc"

    # assets:
    #     favicon: "<link / abs url>"
    #     favicon16x16: "<link / abs url>"
    #     favicon32x32: "<link / abs url>"
    #     apple_touch_icon: "<link / abs url>"
    #     safari_pinned_tab: "<link / abs url>"

    # cover:
    #     hidden: true # hide everywhere but not in structured data
    #     hiddenInList: true # hide on list pages and home
    #     hiddenInSingle: true # hide on single page

    # fuseOpts:
    #     isCaseSensitive: false
    #     shouldSort: true
    #     location: 0
    #     distance: 1000
    #     threshold: 0.4
    #     minMatchCharLength: 0
    #     keys: ["title", "permalink", "summary", "content"]

taxonomies:

markup:
    goldmark:
        renderer:
            unsafe: true
#     highlight:
#         # anchorLineNos: true
#         codeFences: true
#         guessSyntax: true
#         lineNos: true
#         # noClasses: false
#         style: monokai

privacy:
    vimeo:
        disabled: false
        simple: true

    twitter:
        disabled: false
        enableDNT: true
        simple: true

    instagram:
        disabled: false
        simple: true

    youtube:
        disabled: false
        privacyEnhanced: true

services:
    instagram:
        disableInlineCSS: true
    twitter:
        disableInlineCSS: true
