baseURL = "http://example.org/"
languageCode = "en-us"
title = "Jonathan Roth"
theme = "m10c"



[Params]
author = "Jonathan Roth"
description = "I am a rising fifth-year computer science undergraduate student at Rochester Institute of Technology. I have previously worked for Tyber Medical, LLC."
