baseURL = ""
title = "Jonathan Roth"
#themesDir = "../.."
theme = "m10c"
paginate = 8

[menu]
  [[menu.main]]
    identifier = "one"
    name = "One"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "two"
    name = "Two"
    url = "/"
    weight = 2
  [[menu.main]]
    identifier = "three"
    name = "Three"
    url = "/"
    weight = 3
  [[menu.main]]
    identifier = "four"
    name = "Four"
    url = "/"
    weight = 4
  [[menu.main]]
    identifier = "five"
    name = "Five"
    url = "/"
    weight = 5
  [[menu.main]]
    identifier = "six"
    name = "Six"
    url = "/"
    weight = 6

[params]
  author = "Jonathan Roth"
  description = "I am a rising fifth-year computer science undergraduate student at Rochester Institute of Technology. I have previously worked for Tyber Medical, LLC."
  menu_item_separator = " - "
  [[params.social]]
    icon = "github"
    name = "Github"
    url = "https://github.com/JonathanRoth13"
  [[params.social]]
    icon = "linkedin"
    name = "LinkedIn"
    url = "https://www.linkedin.com/in/jonathanroth13/"
  [[params.social]]
    icon = "mail"
    name = "Mail"
    url = "mailto:jonathanroth@protonmail.com"
  # Default theme
  #[params.style]
  #  darkestColor = "#242930"
  #  darkColor = "#353b43"
  #  lightColor = "#afbac4"
  #  lightestColor = "#ffffff"
  #  primaryColor = "#57cc8a"

  # Green theme
  #[params.style]
  #  darkestColor = "#315659"
  #  darkColor = "#253031"
  #  lightColor = "#96a879"
  #  lightestColor = "#fff"
  #  primaryColor = "#dad865"

  # Red theme
  #[params.style]
  #  darkestColor = "#d35050"
  #  darkColor = "#212121"
  #  lightColor = "#d6d6d6"
  #  lightestColor = "#d3d3d3"
  #  primaryColor = "#ffffff"
