baseURL: "/"
title: Jonathan Roth
paginate: 5
theme: hugo-PaperMod
 
enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
# googleAnalytics: UA-123-45

minify:
    disableXML: true
    # minifyOutput: true

languages:
    en:
        languageName: "English"
        languageAltTitle: "English"
        weight: 2
        title: 
        profileMode:
            enabled: true
            title: "Jonathan Roth"
            imageUrl: "avatar.jpg"
            imageWidth: 256
            imageHeight: 256
            subtitle: "grateful for where my love of mathematics has taken me"
            buttons:
                - name: Blog
                  url: posts
                - name: Tags
                  url: tags
        menu:
            main:
                - name: Home
                  url:  #
                  weight: 10
                - name: Archive
                  url: archives/
                  weight: 11
                - name: Tags
                  url: tags
                  weight: 12
                - name: Categories
                  url: categories
                  weight: 13
                - name: Series
                  url: series
                  weight: 14


outputs:
    home:
        - HTML
        - RSS
        - JSON

params:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    description: "Jonathan Roth Blog"
    author: Jonathan Roth

    defaultTheme: night
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    displayFullLangName: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    ShowToc: true
    # comments: false
    images: ["papermod-cover.png"]

    socialIcons:
        - name: github
          url: ""
        - name: linkedin
          url: ""
        - name: email
          url: ""

    # analytics:
    #     google:
    #         SiteVerificationTag: "XYZabc"

    # assets:
    #     favicon: "<link / abs url>"
    #     favicon16x16: "<link / abs url>"
    #     favicon32x32: "<link / abs url>"
    #     apple_touch_icon: "<link / abs url>"
    #     safari_pinned_tab: "<link / abs url>"

    # cover:
    #     hidden: true # hide everywhere but not in structured data
    #     hiddenInList: true # hide on list pages and home
    #     hiddenInSingle: true # hide on single page

    # fuseOpts:
    #     isCaseSensitive: false
    #     shouldSort: true
    #     location: 0
    #     distance: 1000
    #     threshold: 0.4
    #     minMatchCharLength: 0
    #     keys: ["title", "permalink", "summary", "content"]

taxonomies:
    category: categories
    tag: tags
    series: series

markup:
    goldmark:
        renderer:
            unsafe: true
#     highlight:
#         # anchorLineNos: true
#         codeFences: true
#         guessSyntax: true
#         lineNos: true
#         # noClasses: false
#         style: monokai

privacy:
    vimeo:
        disabled: false
        simple: true

    twitter:
        disabled: false
        enableDNT: true
        simple: true

    instagram:
        disabled: false
        simple: true

    youtube:
        disabled: false
        privacyEnhanced: true

services:
    instagram:
        disableInlineCSS: true
    twitter:
        disableInlineCSS: true
